export const recits =
    [{ titre: "Premier article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Deuxime article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Troisième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Quatrième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Cinquième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Quatrième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Quatrième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Quatrième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Quatrième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Quatrième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Quatrième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Quatrième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Quatrième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Quatrième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },
    { titre: "Quatrième article", contenu: "hello c'est mon premier article. On va essayer de faire un affichage cool de cet article." },]